---

- name: Creating kubeconfig to Controller Manager
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://127.0.0.1:6443 \
    --kubeconfig={{ item }}.kubeconfig

    kubectl config set-credentials {% if 'admin' in item -%} {{ item }} {% else %} system:{{ item }} {%- endif %} \
    --client-certificate={{ item }}.pem \
    --client-key={{ item }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ item }}.kubeconfig

    kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user={% if 'admin' in item -%} {{ item }} {% else -%} system:{{ item }} {%- endif %} \
    --kubeconfig={{ item }}.kubeconfig

    kubectl config use-context default --kubeconfig={{ item }}.kubeconfig
  args:
    chdir: /opt
  loop: 
    - kube-controller-manager
    - admin
    - kube-scheduler