---

- name: Create Kube Scheduler CSR
  vars:
    common_name: system:kube-scheduler
    organization: system:kube-scheduler
  template:
    src: common-csr.json.j2
    dest: /opt/kube-scheduler-csr.json

- name: Generate Key and PEM to Kube Scheduler
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -profile=kubernetes \
    kube-scheduler-csr.json | cfssljson -bare kube-scheduler
  args:
    chdir: /opt