---

- name: Create Service Account CSR
  vars:
    common_name: service-accounts
    organization: Kubernetes
  template:
    src: common-csr.json.j2
    dest: /opt/service-account-csr.json

- name: Generate Key and PEM to Service Account
  shell: |
    cfssl gencert \
    -ca=ca.pem \
    -ca-key=ca-key.pem \
    -config=ca-config.json \
    -profile=kubernetes \
    service-account-csr.json | cfssljson -bare service-account
  args:
    chdir: /opt