---

- name: Disable auto upgrade Ubuntu or Debian
  lineinfile:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: '*Unattended-Upgrade*'
    line: 'APT::Periodic::Unattended-Upgrade "0";'
  when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"
