---
# tasks file for pre_prepare
- include: install_kubectl.yaml
- include: hostname.yaml
  when:  lookup('env','USER') != "vagrant"
- include: configure_dns.yaml
- include: disable_ubuntu_auto_upgrade.yaml
#- include: base_packages.yaml