---

- name: Install Weave Net
  template:
    src: coredns.yaml.j2
    dest: /opt/coredns.yaml

- name: Apply coreDNS
  shell: |
    kubectl apply \
     --kubeconfig {{ lookup('env','HOME') }}/.kube/config \
     -f /opt/coredns.yaml