---
- name: "[WARN]"
  debug:
    msg: "Just to remember WeaveNet doesn't work with Iptable 1.8"

#Just to remember WeaveNet doesn't work with Iptable 1.8
- name: Deploy Weave Net
  shell: |
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.IPALLOC_RANGE={{ cluster_cidr }}"