---

- name: Download kube-apiserver
  get_url:
    url: '{{ kube_apiserver_url }}'
    dest: /usr/local/bin/
    mode: 'u=wrx,go=r'

- name: Create /var/lib/kubernetes/ to kube-apiserver
  file:
    path: /var/lib/kubernetes/
    state: directory

- name: Move certificates to /var/lib/kubernetes/ 
  copy:
    src: "/root/{{ item }}"
    dest: /var/lib/kubernetes/ 
    remote_src: yes
  loop:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem 
    - service-account.pem
    - encryption-config.yaml

- name: Configure kube-apiserver unit SystemD service file
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service
  notify: 
    - Reload Systemd Daemon

- name: Restart kube-apiserver service
  systemd:
    name: kube-apiserver
    state: started
    enabled: yes